
// BADGES TYPES
export const CHANGESTATUSHEADER = 'CHANGESTATUSHEADER';
export const CHANGESTATUESBAR = 'CHANGESTATUESBAR';
export const CHANGESTATUSPIE = 'CHANGESTATUSPIE';
export const CHANGESTATUSPROGRESS = 'CHANGESTATUSPROGRESS';
export const CHANGESTATUSTOPCUSTOMERS = 'CHANGESTATUSTOPCUSTOMERS';
export const CHANGESTATUSLINE = 'CHANGESTATUSLINE';
export const CHANGESTATUSTRANSACTIONS = 'CHANGESTATUSTRANSACTIONS';

// CATEGORY TYPES
export const UPDATE_CATEGORY_STATUS = "UPDATE_CATEGORY_STATUS";
export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";
export const REMOVE_ITEM = "REMOVE_ITEM";

// POPUPS TYPES
export const CHANGESTATUSMENU = "CHANGESTATUSMENU";
export const CHANGESTATUSMODE = "CHANGESTATUSMODE";
export const CHANGESTATUSPROFILE = "CHANGESTATUSPROFILE";
export const CHANGESTATUSSETTING = "CHANGESTATUSSETTING";
export const CHANGE_STATUS_ADD_KANBAN = "CHANGE_STATUS_ADD_KANBAN";
export const CHANGESTATUSIMAGE = "CHANGESTATUSIMAGE";
export const CHANGESTATUSFORGETPASSWORD = "CHANGESTATUSFORGETPASSWORD";
export const CHANGESTATUSFORSHOCATEGORY = "CHANGESTATUSFORSHOCATEGORY";
export const CHANGESTATUSFORSHOWBRAND = "CHANGESTATUSFORSHOWBRAND";
export const CHANGE_STATUS_EDIT_KANBAN = "CHANGE_STATUS_EDIT_KANBAN";
//OTHER STATE TYPES
export const ADD_EMAIL_FORGET_PASSWORD = "ADD_EMAIL_FORGET_PASSWORD"; 
export const ADD_KANBAN_DO = "ADD_KANBAN_DO";
export const ADD_NEW_EVENT_CALENDAR_TO_EVENTS = "ADD_NEW_EVENT_CALENDAR_TO_EVENTS";
export const SET_URL_IMAGE_POPUP = "SET_URL_IMAGE_POPUP";
export const SET_ROW_ID = "SET_ROW_ID";
export const SET_ERROR_DATAGRID = "SET_ERROR_DATAGRID";
export const SET_USER_LOGIN = "SET_USER_LOGIN";
export const SET_OPEN_CROP_IMAGE = "SET_OPEN_CROP_IMAGE";
export const SET_IMAGE_AFTER_CROP = "SET_IMAGE_AFTER_CROP";
export const SET_IMAGE_upload = "SET_IMAGE_upload";
export const SET_URL_IMAGE_AFTER_CROP = "SET_URL_IMAGE_AFTER_CROP";
export const SET_IMAGE_NB = "SET_IMAGE_NB";
export const SET_URL_IMAGE1_AFTER_CROP = "SET_URL_IMAGE1_AFTER_CROP";
export const CLEAR_ALL_IMAGES = "CLEAR_ALL_IMAGES";
export const SET_DATA_SHOW_CATEGORY = "SET_DATA_SHOW_CATEGORY";
export const SET_IMAGE1_AFTER_CROP = "SET_IMAGE1_AFTER_CROP";
export const SET_DATA_SHOW_BRAND = "SET_DATA_SHOW_BRAND";
export const CHANGE_THEME_COLOR = "CHANGE_THEME_COLOR";
export const SET_COLUMN_KANBAN = "SET_COLUMN_KANBAN";
export const SET_ITEM_KANBAN = "SET_ITEM_KANBAN";
// SUBCATEGORY TYPES
export const UPDATE_SUBCATEGORY_STATUS = "UPDATE_SUBCATEGORY_STATUS";
export const FETCH_DATA_REQUEST_SUB = "FETCH_DATA_REQUEST_SUB";
export const FETCH_DATA_SUCCESS_SUB = "FETCH_DATA_SUCCESS_SUB";
export const FETCH_DATA_FAILURE_SUB = "FETCH_DATA_FAILURE_SUB";
export const REMOVE_ITEM_SUB = "REMOVE_ITEM_SUB";
// BRANDS TYPES
export const UPDATE_BRAND_STATUS = "UPDATE_BRAND_STATUS";
export const FETCH_DATA_REQUEST_BRAND = "FETCH_DATA_REQUEST_BRAND";
export const FETCH_DATA_SUCCESS_BRAND = "FETCH_DATA_SUCCESS_BRAND";
export const FETCH_DATA_FAILURE_BRAND = "FETCH_DATA_FAILURE_BRAND";
export const REMOVE_ITEM_BRAND = "REMOVE_ITEM_BRAND";

// USERS TYPES

export const FETCH_DATA_REQUEST_USER = "FETCH_DATA_REQUEST_USER";
export const FETCH_DATA_SUCCESS_USER = "FETCH_DATA_SUCCESS_USER";
export const FETCH_DATA_FAILURE_USER = "FETCH_DATA_FAILURE_USER";
export const REMOVE_ITEM_USER = "REMOVE_ITEM_USER";
export const UPDATE_USER_ACTION = "UPDATE_USER_ACTION";

// PRODUCTS TYPES

export const FETCH_DATA_REQUEST_PRODUCT = "FETCH_DATA_REQUEST_PRODUCT";
export const FETCH_DATA_SUCCESS_PRODUCT = "FETCH_DATA_SUCCESS_PRODUCT";
export const FETCH_DATA_FAILURE_PRODUCT = "FETCH_DATA_FAILURE_PRODUCT";
export const REMOVE_ITEM_PRODUCT = 'REMOVE_ITEM_PRODUCT';

// COUPON TYPES

export const FETCH_DATA_REQUEST_COUPON = "FETCH_DATA_REQUEST_COUPON";
export const FETCH_DATA_SUCCESS_COUPON = "FETCH_DATA_SUCCESS_COUPON";
export const FETCH_DATA_FAILURE_COUPON = "FETCH_DATA_FAILURE_COUPON";
export const REMOVE_ITEM_COUPON = "REMOVE_ITEM_COUPON";

// REVIEW TYPES

export const FETCH_DATA_REQUEST_REVIEW = "FETCH_DATA_REQUEST_REVIEW";
export const FETCH_DATA_SUCCESS_REVIEW = "FETCH_DATA_SUCCESS_REVIEW";
export const FETCH_DATA_FAILURE_REVIEW = "FETCH_DATA_FAILURE_REVIEW";
export const REMOVE_ITEM_REVIEW = "REMOVE_ITEM_REVIEW";
export const UPDATE_REVIEW_USER_ACTION = "UPDATE_REVIEW_USER_ACTION";